name: Push code/docs to Huggingface

on:
  push:
    branches: [main]
    paths:
      - "modelcard.md"
      - "docs/**"
      - "README.md"
      - ".github/workflows/**"
      - "src/**"
      - "notebooks/**"

permissions:
  contents: write

env:
  HF_REPO: "felixombura/maxai-finance-cash"
  SOURCE_ROOT: "."
  DEST_ROOT: "."

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout GitHub repo (with LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install git-lfs (for model artifacts) and dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-lfs || true
          git lfs install || true

      - name: Verify HF token present
        run: |
          if [ -z "${HF_TOKEN}" ]; then
            echo "ERROR: HF_TOKEN secret not found. Add it in Settings -> Secrets -> Actions"
            exit 1
          fi

      - name: Create temporary working dir
        run: |
          rm -rf hf-repo || true
          mkdir hf-repo

      - name: Clone Hugging Face repo with token
        run: |
          set -e
          echo "Cloning https://huggingface.co/${HF_REPO} ..."
          # Token must have write access
          git clone https://x-access-token:${HF_TOKEN}@huggingface.co/${HF_REPO} hf-repo
          ls -la hf-repo

      - name: Copy files to HF repo (selective)
        run: |
          set -e
          # Example: copy modelcard, readme, src, notebooks, docs
          cp -av modelcard.md hf-repo/ || true
          cp -av README.md hf-repo/ || true
          cp -av docs/ hf-repo/ || true
          cp -av src/ hf-repo/src || true
          cp -av notebooks/ hf-repo/notebooks || true
          # Note: adjust the cp lines above to match what you want to sync

      - name: Commit & push if changed
        run: |
          set -e
          cd hf-repo
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Sync from GitHub: auto-update code/docs (via Actions)"
          # Push to HF main (origin created by clone)
          git push origin HEAD:main

      - name: Done
        run: echo "Pushed changes to https://huggingface.co/${HF_REPO}"
